### ISSUE TITLE
Grow 的总量信息不链接钱包也应该展示

### ISSUE THREAD

**Issue by jolestar** [rooch-network/grow-bitcoin#14]
<img width="1156" alt="Screenshot 2024-11-21 at 09 52 02" src="https://github.com/user-attachments/assets/5d8c9001-d12c-45de-b84f-3e386b972681">

**Comment by wow-sven** [comment]
Here is the grow balance of the current address

**Comment by jolestar** [comment]
不展示，或者提示链接钱包？
