### ISSUE TITLE
BitXP balance different between portal and grow bitcoin

### ISSUE THREAD

**Issue by jolestar** [rooch-network/grow-bitcoin#28]
https://grow.rooch.network/portfolio
https://portal.rooch.network/account

**Comment by lispking** [comment]
assign to me, thx.

**Comment by jolestar** [comment]
Maybe it is a portal issue https://github.com/rooch-network/rooch/tree/main/infra/rooch-portal-v2

**Comment by lispking** [comment]
原因是后端rpc api: rooch_getBalances接口返回的时候，decimals设置为1，导致portal展示的时候少了10倍，正在跟踪了rpc server代码（然后发现rooch代码一开始，机器内存真心顶不住😂

**Comment by jolestar** [comment]
We ignore the BitXP decimal
