### ISSUE TITLE
feat: 建议增加一键 stake 和 claim 全部能力

### ISSUE THREAD

**Issue by lispking** [rooch-network/grow-bitcoin#29]
https://grow.rooch.network/stake/self 页面点击太累了，能不能优化成全部显示出来

然后，再加一个一键 stake 和 claim 全部的功能

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/d3be2529-169d-4f5e-bf95-9bed3e9bd94f">

**Comment by jolestar** [comment]
这个需求还需要给

https://github.com/rooch-network/rooch/blob/main/apps/grow_bitcoin/sources/grow_bitcoin.move

增加一个批量的 harvest 方法。
